// <auto-generated />
using System;
using AjaxDemoASPMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AjaxDemoASPMVC.Migrations
{
    [DbContext(typeof(EmployeeDbContext1))]
    [Migration("20230210095758_addskill")]
    partial class addskill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AjaxDemoASPMVC.Models.Department1", b =>
                {
                    b.Property<int>("Department1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Department1Id"));

                    b.Property<string>("Dept_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Department1Id");

                    b.HasIndex("Dept_Name")
                        .IsUnique();

                    b.ToTable("departments1");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.Designation1", b =>
                {
                    b.Property<int>("Designation1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Designation1Id"));

                    b.Property<string>("Designation_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Designation1Id");

                    b.HasIndex("Designation_Name")
                        .IsUnique();

                    b.ToTable("designations1");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.Employee1", b =>
                {
                    b.Property<int>("Employee1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee1Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Designation1Id")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Gender1Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<int>("depaartment1Department1Id")
                        .HasColumnType("int");

                    b.HasKey("Employee1Id");

                    b.HasIndex("Designation1Id");

                    b.HasIndex("Gender1Id");

                    b.HasIndex("depaartment1Department1Id");

                    b.ToTable("employees1");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.EmployeeSkill1", b =>
                {
                    b.Property<int>("Empid")
                        .HasColumnType("int");

                    b.Property<int>("Skillid")
                        .HasColumnType("int");

                    b.HasKey("Empid", "Skillid");

                    b.HasIndex("Skillid");

                    b.ToTable("employeeskills1");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.Gender1", b =>
                {
                    b.Property<int>("Gender1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gender1Id"));

                    b.Property<string>("Gender_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Gender1Id");

                    b.HasIndex("Gender_Name")
                        .IsUnique();

                    b.ToTable("genders1");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.Skill1", b =>
                {
                    b.Property<int>("Skill1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Skill1Id"));

                    b.Property<string>("Skill_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Skill1Id");

                    b.ToTable("skills1");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.Employee1", b =>
                {
                    b.HasOne("AjaxDemoASPMVC.Models.Designation1", "designation1")
                        .WithMany()
                        .HasForeignKey("Designation1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AjaxDemoASPMVC.Models.Gender1", "gender1")
                        .WithMany()
                        .HasForeignKey("Gender1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AjaxDemoASPMVC.Models.Department1", "depaartment1")
                        .WithMany()
                        .HasForeignKey("depaartment1Department1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depaartment1");

                    b.Navigation("designation1");

                    b.Navigation("gender1");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.EmployeeSkill1", b =>
                {
                    b.HasOne("AjaxDemoASPMVC.Models.Employee1", "emp")
                        .WithMany("employeeSkill1")
                        .HasForeignKey("Empid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AjaxDemoASPMVC.Models.Skill1", "skill1s")
                        .WithMany("employeeSkill1")
                        .HasForeignKey("Skillid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("emp");

                    b.Navigation("skill1s");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.Employee1", b =>
                {
                    b.Navigation("employeeSkill1");
                });

            modelBuilder.Entity("AjaxDemoASPMVC.Models.Skill1", b =>
                {
                    b.Navigation("employeeSkill1");
                });
#pragma warning restore 612, 618
        }
    }
}
